### PR TITLE
Issue4/release1.0.0

### PR DESCRIPTION
**Pull request by Mackiovello**
Adapt Cashier to starpack and add CONTRIBUTING.md

### CODE REVIEW

**Comment by Mackiovello** [comment]
The ZIP files created by this setup are not accepted by the old warehouse. 

I get this error `[Cashier-1.0.0.zip] Failed to find file in package, {0}`

**Comment by warpech** [comment]
> I get this error [Cashier-1.0.0.zip] Failed to find file in package, {0}

You get this error when there is no app icon in the package. Try to create a file `Cashier.png` and put it next to csproj. Let me know if this helps

**Comment by Mackiovello** [comment]
Adding a Cashier.png fixes the issue. My only remaining question is how I would add the description to the warehouse?

**Comment by warpech** [comment]
Looking good. Merged, thanks!

**Pull request merged**
